### ISSUE TITLE
ColorFilter block gives OpenCV error

### ISSUE THREAD

**Issue by toshan-luktuke** [JdeRobot/VisualCircuit#211]
Running a simple example of ColorFilter gives the following error:

```shell
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/toshan/Downloads/Untitled/modules/ColorFilter2001.py", line 19, in main
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgproc/src/color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function 'cv::impl::{anonymous}::CvtHelper<VScn, VDcn, VDepth, sizePolicy>::CvtHelper(cv::InputArray, cv::OutputArray, int) [with VScn = cv::impl::{anonymous}::Set<3, 4>; VDcn = cv::impl::{anonymous}::Set<3>; VDepth = cv::impl::{anonymous}::Set<0, 5>; cv::impl::{anonymous}::SizePolicy sizePolicy = cv::impl::<unnamed>::NONE; cv::InputArray = const cv::_InputArray&; cv::OutputArray = const cv::_OutputArray&]'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1
```

OpenCV version: 4.7.0
OS: Ubuntu 20.04
Circuit Image:
![image](https://user-images.githubusercontent.com/31101072/216834022-68f512dc-6e62-4c53-8e82-1c132ded8c59.png)

**Comment by siddheshsingh26** [comment]
### Hey, I was working on this issue and I suspect it may be a system-specific problem since I didn't encounter the error as you did.
#### This is my system configuration:
- OpenCV version: 4.2.0
- OS : Pop_os 20.04

#### Circuit Image:
![Screenshot from 2023-02-16 23-29-49](https://user-images.githubusercontent.com/105278190/219449341-3a5cdb47-b5a8-461f-9025-0098d10ada66.png)
#### Output
![Screenshot from 2023-02-17 01-03-27](https://user-images.githubusercontent.com/105278190/219468530-070edb6e-4f88-4cb8-8adf-41307fa476e7.png)

#### Here are the steps I followed:
- First, I created the circuit by using three blocks: the camera and screen block from Drivers->OpenCV, and the color filter from Processing->OpenCV.
- Next, I compiled the main.py file after building the circuit.
- The output displayed the image with the blue color filtered out.

**Comment by toshan-luktuke** [comment]
So looking into it further, this issue seems to occur when due to simultaneous execution of blocks, the `Colour Filter` block tries to execute without an image being supplied to it. In this case the `if frame == None` is not enough and we need to add a new way to check for existence/non-existence of the image object

**Comment by toshan-luktuke** [comment]
Currently the check:
` if frame.shape == ()` seems to be working fine. However I don't know if this is the best way to check. So this'll need some investigation

**Comment by siddheshsingh26** [comment]
Yes, I'll try to find another way to this issue if possible.

**Comment by prawnsgupta** [comment]
@VarnikaMishra — you mentioned in March that you had a verified guard-clause fix ready. Are you still planning to submit it? If so I'll stay out of the way; if not, I'd like to take this one.

@BkPankaj @jmplaza — if @VarnikaMishra isn't continuing, could you assign this to me? The thread has been open since 2023 and both original participants have been inactive on it for a while.

Two things I'd want to settle before proposing a fix, since the earlier discussion landed on if frame.shape == () as a workaround that nobody was happy with:

The None check in ColorFilter.py is not the only gap. inputs.read_image() returns None only while the wire does not exist yet; once the producer has created the wire but before it has written a frame, the reader gets a real array whose shape comes from a shape wire that may not be populated. So the guard needs to cover an existing-but-empty wire, not just a missing one.

The reported error is scn is 1, i.e. a single-channel array reaching cv2.cvtColor(..., COLOR_BGR2HSV). That is also exactly what share_image() produces for a 2-D input — it reshapes to (h, w, 1) — so a grayscale upstream block would trigger the same error through a completely different path. Worth confirming which of the two the original circuit hit before fixing only one of them.

I can reproduce both cases and put the guard in Inputs/Outputs rather than in each block, so the other CV blocks get it too. Let me know if that's the direction you want.

**Comment by VarnikaMishra** [comment]
> [@VarnikaMishra](https://github.com/VarnikaMishra) — you mentioned in March that you had a verified guard-clause fix ready. Are you still planning to submit it? If so I'll stay out of the way; if not, I'd like to take this one.
> 
> [@BkPankaj](https://github.com/BkPankaj) [@jmplaza](https://github.com/jmplaza) — if [@VarnikaMishra](https://github.com/VarnikaMishra) isn't continuing, could you assign this to me? The thread has been open since 2023 and both original participants have been inactive on it for a while.
> 
> Two things I'd want to settle before proposing a fix, since the earlier discussion landed on if frame.shape == () as a workaround that nobody was happy with:
> 
> The None check in ColorFilter.py is not the only gap. inputs.read_image() returns None only while the wire does not exist yet; once the producer has created the wire but before it has written a frame, the reader gets a real array whose shape comes from a shape wire that may not be populated. So the guard needs to cover an existing-but-empty wire, not just a missing one.
> 
> The reported error is scn is 1, i.e. a single-channel array reaching cv2.cvtColor(..., COLOR_BGR2HSV). That is also exactly what share_image() produces for a 2-D input — it reshapes to (h, w, 1) — so a grayscale upstream block would trigger the same error through a completely different path. Worth confirming which of the two the original circuit hit before fixing only one of them.
> 
> I can reproduce both cases and put the guard in Inputs/Outputs rather than in each block, so the other CV blocks get it too. Let me know if that's the direction you want.

Hi @prawnsgupta , I had solved this issue, that PR has been merged. The mentors maybe forgot to close the issue.
This project is really good, you can try solving other issues.
